[package]
name = "img2laser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.10", features = ["derive"] }
image = "0.24.5"
plotters = "0.3.4"
svg = "0.13.0"
